EmployeeManagementMVC/Models/ErrorViewModel.cs
using System;

namespace EmployeeManagementMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EmployeeManagementMVC/Controllers/EmpController.cs
using BusinessLayer.Interface;
using CommonLayer;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace EmployeeManagementMVC.Controllers
{
    public class EmpController : Controller
    {
        private readonly IEmpBusiness empBusiness;
        public EmpController(IEmpBusiness empBusiness)
        {
            this.empBusiness = empBusiness;
        }

        public IActionResult Index()
        {
            List<EmployeeModel> lstEmployee = new List<EmployeeModel>();
            lstEmployee = empBusiness.GetAllEmployee().ToList();

            return View(lstEmployee);

        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost("Emp/Create")]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind] EmployeeModel employee)
        {
            string message = TempData["errorMessage"].ToString();
            if (ModelState.IsValid)
            {
                empBusiness.AddEmployee(employee);
                return RedirectToAction("Index");
            }
            return View(employee);
        }

        [HttpGet]
        public IActionResult Edit(int employeeId)
        {
            try
            {
                EmployeeModel employee = empBusiness.GetById(employeeId);
                if (employee.EmployeeId == 0)
                {
                    TempData["errorMessage"] = $"Employee deatils not found with id: {employeeId}";
                    return RedirectToAction("Index");
                }
                return View(employee);
            }
            catch (System.Exception)
            {

                throw;
            }
        }
        [HttpPost("Emp/Edit{employee}")]
        public IActionResult Edit(EmployeeModel employee)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    TempData["errorMessage"] = "Model data is invalid";
                    return View();
                }
                bool result = empBusiness.UpdateEmployee(employee);
                if(!result)
                {
                    TempData["errorMessage"] = "Unable to update Employee";
                    return View();
                }
                TempData["successMessage"] = "Employee details updated";
                return RedirectToAction("Index");
            }
            catch (System.Exception)
            {

                throw;
            }
        }
        [HttpGet]
        public IActionResult Delete(int employeeId)
        {
            try
            {
                EmployeeModel employee = empBusiness.GetById(employeeId);
                if (employee.EmployeeId == 0)
                {
                    TempData["errorMessage"] = $"Employee deatils not found with id : {employeeId}.";
                    return RedirectToAction("Index");
                }
                return View(employee);
            }
            catch (System.Exception)
            {

                throw;
            }
        }
        [HttpPost("Emp/Delete"),ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int employeeId)
        {
            try
            {
                bool result = empBusiness.DeleteEmployee(employeeId);
                if (!result)
                {
                    TempData["errorMessage"] = "Unable to Delete Employee";
                    return View();
                }
                TempData["successMessage"] = "Employee details deleted";
                return RedirectToAction("Index");
            }
            catch (System.Exception)
            {

                throw;
            }
        }
        [HttpGet]
        public IActionResult Details()
        {
            try
            {
                int empId = (int)HttpContext.Session.GetInt32("EmployeeId");
                string empName = HttpContext.Session.GetString("Name");
                EmployeeModel employee = empBusiness.GetById(empId);
                if (employee.EmployeeId == 0)
                {
                    TempData["errorMessage"] = $"Employee deatils not found with id: {empId}";
                    return RedirectToAction("Index");
                }
                return View(employee);
            }
            catch (System.Exception)
            {

                throw;
            }
        }
        [HttpGet]
        public IActionResult Login()
        {
            var employeeLogin = new EmployeeLogin();
            return View(employeeLogin);
        }
        [HttpPost]
        public IActionResult Login([Bind] EmployeeLogin employeeLogin)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    TempData["errorMessage"] = "Model data is invalid";
                    return View();
                }
                EmployeeModel employee = empBusiness.LogInEmployee(employeeLogin);
                if (employee.EmployeeId == 0)
                {
                    TempData["errorMessage"] = $"Employee deatils not found with id : {employeeLogin.EmployeeId} .Please Register!!";
                    return RedirectToAction("Create");
                }
                if (employee != null)
                {
                    HttpContext.Session.SetInt32("EmployeeId", employee.EmployeeId);
                    HttpContext.Session.SetString("Name", employee.Name);
                    return RedirectToAction("Details");
                }
                else
                {
                    return View(employeeLogin);
                }

            }
            catch (System.Exception)
            {

                throw;
            }
        }
    }
}

EmployeeManagementMVC/Controllers/HomeController.cs
using EmployeeManagementMVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace EmployeeManagementMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EmployeeManagementMVC/Views/Emp/Create.cshtml
@model CommonLayer.EmployeeModel

@{
    ViewData["Title"] = "Create";
    
}

<link href="~/css/create.css" rel="stylesheet" />
<div class="centerLink">
<h1 class="headerStyle">Add Employee </h1>
<div class="row">
        <div >
            @if (TempData["errorMessage"] != null)
            {
                <p style="color:red;font-weight: bold;font-family: Arial,Verdana,sans-serif;">@TempData["errorMessage"]</p>
            }
    </div>
    <div class="col-md-4 form-align formContent">
        <form asp-action="Create" >
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @* <div class="form-group">
                <label asp-for="EmployeeId" class="control-label"></label>
                <input asp-for="EmployeeId" class="form-control" />
                <span asp-validation-for="EmployeeId" class="text-danger"></span>
            </div> *@
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger nameEntity"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProfileImage" class="control-label"></label>
                <div>
                    @Html.RadioButtonFor(model => model.ProfileImage, "~/Assets/imga.png")
                    <img class=" Profile-image-1" src = "~/Assets/imga.png" />
                    @Html.RadioButtonFor(model => model.ProfileImage, "~/Assets/imgb.png")
                    <img class=" Profile-image-1" src="~/Assets/imgb.png" />
                    @Html.RadioButtonFor(model => model.ProfileImage, "~/Assets/imgc.png")
                    <img class=" Profile-image-1" src="~/Assets/imgc.png" />
                    @Html.RadioButtonFor(model => model.ProfileImage, "~/Assets/imgd.png")
                    <img class=" Profile-image-1" src="~/Assets/imgd.png" />
                </div>
                <span asp-validation-for="ProfileImage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <div>
                    @Html.RadioButtonFor(m => m.Gender,"M") M
                    @Html.RadioButtonFor(m => m.Gender,"F") F
                </div>
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Department" class="control-label"></label>
                <select asp-for="Department" class="form-control">
                    <option value="">--- Select Department ---</option>
                    <option value="Human Resource">Human Resource</option>
                    <option value="Finance">Finance</option>
                    <option value="Information Technology">Information Technology</option>
                    <option value="DevOps">DevOps</option>
                </select>
                <span asp-validation-for="Department" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Salary" class="control-label"></label>
                <input asp-for="Salary" class="form-control" />
                <span asp-validation-for="Salary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Notes" class="control-label"></label>
                <input asp-for="Notes" class="form-control" />
                <span asp-validation-for="Notes" class="text-danger"></span>
            </div>
            <div class="form-group ">
                <input type="submit" value="Create" class="submitButton" />
            </div>
        </form>
    </div>
</div>

    <div>
    <a asp-action="Index"class="indexLink">Back to List</a>
    <p>&nbsp;</p>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

</div>

EmployeeManagementMVC/Views/Emp/Delete.cshtml
@model CommonLayer.EmployeeModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Employee</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmployeeId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmployeeId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProfileImage)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProfileImage)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Department)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Department)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Salary)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Salary)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Notes)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Notes)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="EmployeeId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

EmployeeManagementMVC/Views/Emp/Details.cshtml
@model CommonLayer.EmployeeModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>EmployeeModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmployeeId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmployeeId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProfileImage)
        </dt>
        <dd class = "col-sm-10">
            <img src="@Url.Content(Model.ProfileImage)"/>
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Department)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Department)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Salary)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Salary)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Notes)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Notes)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

EmployeeManagementMVC/Views/Emp/Edit.cshtml
@model CommonLayer.EmployeeModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>EmployeeModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                @* <label asp-for="EmployeeId" class="control-label"></label> *@
                <input asp-for="EmployeeId" class="form-control" type ="hidden" readonly/>
                <span asp-validation-for="EmployeeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProfileImage" class="control-label"></label>
                <div>
                    @Html.RadioButtonFor(model => model.ProfileImage, "~/Assets/imga.png")
                    <img class=" Profile-image-1" src="~/Assets/imga.png" />
                    @Html.RadioButtonFor(model => model.ProfileImage, "~/Assets/imgb.png")
                    <img class=" Profile-image-1" src="~/Assets/imgb.png" />
                    @Html.RadioButtonFor(model => model.ProfileImage, "~/Assets/imgc.png")
                    <img class=" Profile-image-1" src="~/Assets/imgc.png" />
                    @Html.RadioButtonFor(model => model.ProfileImage, "~/Assets/imgd.png")
                    <img class=" Profile-image-1" src="~/Assets/imgd.png" />
                </div>
                <span asp-validation-for="ProfileImage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <div>
                    @Html.RadioButtonFor(m => m.Gender,"M") M
                    @Html.RadioButtonFor(m => m.Gender,"F") F
                </div>
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Department" class="control-label"></label>
                <select asp-for="Department" class="form-control">
                    <option value="">--- Select Department ---</option>
                    <option value="Human Resource">Human Resource</option>
                    <option value="Finance">Finance</option>
                    <option value="Information Technology">Information Technology</option>
                    <option value="DevOps">DevOps</option>
                </select>
                <span asp-validation-for="Department" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Salary" class="control-label"></label>
                <input asp-for="Salary" class="form-control" />
                <span asp-validation-for="Salary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" readonly/>
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Notes" class="control-label"></label>
                <input asp-for="Notes" class="form-control" />
                <span asp-validation-for="Notes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EmployeeManagementMVC/Views/Emp/Index.cshtml
@model IEnumerable<CommonLayer.EmployeeModel>

@{
    ViewData["Title"] = "Index";
}

<link href="~/css/index.css" rel="stylesheet" />

<h1>List of Employees </h1>

<p >
    <a asp-action="Create" class="createLink">Create New</a>
</p>
<table class="table">
    <thead class="tableLink">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.EmployeeId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProfileImage)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Department)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Salary)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Notes)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.EmployeeId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                <img src="@Url.Content(item.ProfileImage)" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Department)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Salary)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Notes)
            </td>
                <td class="buttonWidth">
                <span class="editlink">
                    @Html.ActionLink("Edit", "Edit", new { employeeId = item.EmployeeId  }) 
                    </span> &nbsp; | &nbsp;
                <span class="editlink">
                    @Html.ActionLink("Details", "Details", new { employeeId = item.EmployeeId })
                    </span> &nbsp | &nbsp;
                
                <span class="editlink">
                    @Html.ActionLink("Delete", "Delete", new { employeeId = item.EmployeeId })
                </span> 
            </td>
        </tr>
}
    </tbody>
</table>

EmployeeManagementMVC/Views/Emp/Login.cshtml
@model CommonLayer.EmployeeLogin

@{
    ViewData["Title"] = "Login";
}
<link href="~/css/login.css" rel="stylesheet" />
<div class="centerLink">
<h1 class="headerStyle">Sign in </h1>
<h4>Use your Employee Account</h4>
<div class="row">
        <div class="formContent">
        <form asp-action="Login">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="EmployeeId" class="control-label"></label>
                <input asp-for="EmployeeId" class="form-control" />
                <span asp-validation-for="EmployeeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Sing in" class="detaiLink" />
            </div>
        </form>
    </div>
</div>

<div style=" padding-bottom:20px;display:flex;justify-content:center;">
    <div>
            <p>New Employee? </p> 
    </div>
        &nbsp;&nbsp;
        <div>
         <a asp-action="Create" class="createLink">Sign up</a>
    </div>
</div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EmployeeManagementMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

EmployeeManagementMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] EmployeeManagementMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body style="background-color: lightgray;">
    <header style ="background-color: lightgray;">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-lightgray border-bottom box-shadow mb-3">
            <div class="container">
                <div class="imgHead">
                    <img src="~/Assets/MVC.png" />
                    <div class="headContent">
                        <span>
                            <a asp-area="" asp-controller="Home" asp-action="Index" class="titleStyle">Employee</a>
                        </span>
                        <span>
                            <a  asp-area="" asp-controller="Home" asp-action="Index" class="titleStyle">Management</a>
                        </span>
                    </div>
                </div>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Emp" asp-action="Index">Employees</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3" >
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - EmployeeManagementMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>